/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.parser;

import interpreter.node.*;
import interpreter.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLBrk(@SuppressWarnings("unused") TLBrk node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRBrk(@SuppressWarnings("unused") TRBrk node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDash(@SuppressWarnings("unused") TDash node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTilde(@SuppressWarnings("unused") TTilde node)
    {
        this.index = 5;
    }

    @Override
    public void caseTAuthor(@SuppressWarnings("unused") TAuthor node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTitle(@SuppressWarnings("unused") TTitle node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDate(@SuppressWarnings("unused") TDate node)
    {
        this.index = 8;
    }

    @Override
    public void caseTImage(@SuppressWarnings("unused") TImage node)
    {
        this.index = 9;
    }

    @Override
    public void caseTLink(@SuppressWarnings("unused") TLink node)
    {
        this.index = 10;
    }

    @Override
    public void caseTBold(@SuppressWarnings("unused") TBold node)
    {
        this.index = 11;
    }

    @Override
    public void caseTItalic(@SuppressWarnings("unused") TItalic node)
    {
        this.index = 12;
    }

    @Override
    public void caseTEmail(@SuppressWarnings("unused") TEmail node)
    {
        this.index = 13;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 14;
    }

    @Override
    public void caseTList(@SuppressWarnings("unused") TList node)
    {
        this.index = 15;
    }

    @Override
    public void caseTTable(@SuppressWarnings("unused") TTable node)
    {
        this.index = 16;
    }

    @Override
    public void caseTFontSize(@SuppressWarnings("unused") TFontSize node)
    {
        this.index = 17;
    }

    @Override
    public void caseTTr(@SuppressWarnings("unused") TTr node)
    {
        this.index = 18;
    }

    @Override
    public void caseTTd(@SuppressWarnings("unused") TTd node)
    {
        this.index = 19;
    }

    @Override
    public void caseTTh(@SuppressWarnings("unused") TTh node)
    {
        this.index = 20;
    }

    @Override
    public void caseTPlainText(@SuppressWarnings("unused") TPlainText node)
    {
        this.index = 21;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 22;
    }
}
