/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import java.util.*;
import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class ADocument extends PDocument
{
    private final LinkedList<PBlock> _blocks_ = new LinkedList<PBlock>();

    public ADocument()
    {
        // Constructor
    }

    public ADocument(
        @SuppressWarnings("hiding") List<?> _blocks_)
    {
        // Constructor
        setBlocks(_blocks_);

    }

    @Override
    public Object clone()
    {
        return new ADocument(
            cloneList(this._blocks_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADocument(this);
    }

    public LinkedList<PBlock> getBlocks()
    {
        return this._blocks_;
    }

    public void setBlocks(List<?> list)
    {
        for(PBlock e : this._blocks_)
        {
            e.parent(null);
        }
        this._blocks_.clear();

        for(Object obj_e : list)
        {
            PBlock e = (PBlock) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._blocks_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blocks_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blocks_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PBlock> i = this._blocks_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PBlock) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
