/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class APlainTextTerminal extends PTerminal
{
    private TPlainText _plainText_;

    public APlainTextTerminal()
    {
        // Constructor
    }

    public APlainTextTerminal(
        @SuppressWarnings("hiding") TPlainText _plainText_)
    {
        // Constructor
        setPlainText(_plainText_);

    }

    @Override
    public Object clone()
    {
        return new APlainTextTerminal(
            cloneNode(this._plainText_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlainTextTerminal(this);
    }

    public TPlainText getPlainText()
    {
        return this._plainText_;
    }

    public void setPlainText(TPlainText node)
    {
        if(this._plainText_ != null)
        {
            this._plainText_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plainText_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plainText_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plainText_ == child)
        {
            this._plainText_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plainText_ == oldChild)
        {
            setPlainText((TPlainText) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
