/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TAuthor extends Token
{
    public TAuthor()
    {
        super.setText("author");
    }

    public TAuthor(int line, int pos)
    {
        super.setText("author");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAuthor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAuthor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAuthor text.");
    }
}
