/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TBold extends Token
{
    public TBold()
    {
        super.setText("bold");
    }

    public TBold(int line, int pos)
    {
        super.setText("bold");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBold(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBold(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBold text.");
    }
}
