/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TDate extends Token
{
    public TDate()
    {
        super.setText("date");
    }

    public TDate(int line, int pos)
    {
        super.setText("date");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDate(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDate text.");
    }
}
