/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TFontSize extends Token
{
    public TFontSize()
    {
        super.setText("H1");
    }

    public TFontSize(int line, int pos)
    {
        super.setText("H1");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFontSize(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFontSize(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFontSize text.");
    }
}
