/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TImage extends Token
{
    public TImage()
    {
        super.setText("image");
    }

    public TImage(int line, int pos)
    {
        super.setText("image");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TImage(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImage(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TImage text.");
    }
}
