/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TTd extends Token
{
    public TTd()
    {
        super.setText("data");
    }

    public TTd(int line, int pos)
    {
        super.setText("data");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTd(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTd text.");
    }
}
