/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TTitle extends Token
{
    public TTitle()
    {
        super.setText("title");
    }

    public TTitle(int line, int pos)
    {
        super.setText("title");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTitle(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTitle(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTitle text.");
    }
}
