/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.node;

import interpreter.analysis.*;

@SuppressWarnings("nls")
public final class TTr extends Token
{
    public TTr()
    {
        super.setText("row");
    }

    public TTr(int line, int pos)
    {
        super.setText("row");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTr(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTr text.");
    }
}
