/* This file was generated by SableCC (http://www.sablecc.org/). */

package interpreter.analysis;

import java.util.*;
import interpreter.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADocument(ADocument node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAuthorBlock(AAuthorBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATitleBlock(ATitleBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADateBlock(ADateBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFontSizeBlock(AFontSizeBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoldBlock(ABoldBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAItalicBlock(AItalicBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAImageBlock(AImageBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALinkBlock(ALinkBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEmailBlock(AEmailBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParaBlock(AParaBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListBlock(AListBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATableBlock(ATableBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListItem(AListItem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATableRow(ATableRow node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATdTableItem(ATdTableItem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAThTableItem(AThTableItem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATerminalInline(ATerminalInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAuthorInline(AAuthorInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATitleInline(ATitleInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADateInline(ADateInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEmailInline(AEmailInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAImageInline(AImageInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALinkInline(ALinkInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoldInline(ABoldInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAItalicInline(AItalicInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFontSizeInline(AFontSizeInline node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPlainTextTerminal(APlainTextTerminal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInlineTerminal(AInlineTerminal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBrk(TLBrk node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBrk(TRBrk node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDash(TDash node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTilde(TTilde node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAuthor(TAuthor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTitle(TTitle node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDate(TDate node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTImage(TImage node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLink(TLink node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBold(TBold node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTItalic(TItalic node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEmail(TEmail node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPara(TPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTList(TList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTable(TTable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFontSize(TFontSize node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTr(TTr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTd(TTd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTh(TTh node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlainText(TPlainText node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
